import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml"  ]

[font]
size = 10 

[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 0
padding.y = 0
decorations = "None"
opacity = 0.97

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
